services:
  graffiti-pod:
    ports:
      - 3000:3000
    # Print instructions then hang the container
    entrypoint:
      [
        "sh",
        "-c",
        "echo 'Container up! In another tab run\nsudo docker compose exec graffiti-pod sh\nto enter the container.' && tail -f /dev/null",
      ]

  couchdb:
    ports:
      - 5984:5984
