version: "3.8"

services:
  nginx:
    container_name: graffiti-nginx
    image: nginx:1.25.3-alpine-slim
    ports:
      - 443:443
      # Unused port so we don't block 80 for certbot
      - 404:80
    environment:
      DOMAIN: ${DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

  graffiti-pod:
    entrypoint: ["npm", "run", "start"]
